services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-docker-compose
    ports:
      - "11430:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

volumes:
  open-webui: